# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-07-01 20:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(max_length=10)),
                ('food_title', models.CharField(max_length=250)),
                ('is_favorite', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Potato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('origin', models.CharField(max_length=500)),
                ('pronounced', models.CharField(max_length=100)),
                ('picture', models.FileField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='fact',
            name='potato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spuds.Potato'),
        ),
    ]
