# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-07-01 23:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spuds', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fact',
            old_name='food_title',
            new_name='fact_title',
        ),
    ]
